export default {
    initial: 1,
    beforeHtml: 2,
    beforeHead: 3,
    inHead: 4,
    inHeadNoScript: 5,
    afterHead: 6,
    inBody: 7,
    text: 8,
    inTable: 9,
    inTableText: 10,
    inCaption: 11,
    inColumnGroup: 12,
    inTableBody: 13,
    inRow: 14,
    inCell: 15,
    inSelect: 16,
    inSelectInTable: 17,
    inTemplate: 18,
    afterBody: 19,
    inFrameset: 20,
    afterFrameset: 21,
    afterAfterBody: 22,
    afterAfterFrameset: 23
};
