export default {
    data: 1,
    rcdata: 2,
    rawtext: 3,
    scriptData: 4,
    plaintext: 5,
    tagOpen: 6,
    endTagOpen: 7,
    tagName: 8,

    rcdataLessThanSign: 9,
    rcdataEndTagOpen: 10,
    rcDataEndTagName: 11,

    rawtextLessThanSign: 12,
    rawtextEndTagOpen: 13,
    rawtextEndTagName: 14,

    scriptDataLessThanSign: 15,
    scriptDataEndTagOpen: 16,
    scriptDataEndTagName: 17,
    scriptDataEscapeStart: 18,
    scriptDataEscapeStartDash: 19,
    scriptDataEscaped: 20,
    scriptDataEscapedDash: 21,
    scriptDataEscapedDashDash: 22,
    scriptDataEscapedLessThanSign: 23,
    scriptDataEscapedEndTagOpen: 24,
    scriptDataEscapedEndTagName: 25,
    scriptDataDoubleEscapeStart: 26,
    scriptDataDoubleEscaped: 27,
    scriptDataDoubleEscapedDash: 28,
    scriptDataDoubleEscapedDashDash: 29,
    scriptDataDoubleEscapedLessThanSign: 30,
    scriptDataDoubleEscapeEnd: 31,

    beforeAttributeName: 32,
    attributeName: 33,
    afterAttributeName: 34,
    beforeAttributeValue: 35,
    attributeValueDoubleQuoted: 36,
    attributeValueSingleQuoted: 37,
    attributeValueUnquoted: 38,
    afterAttributeValueQuoted: 39,

    selfClosingStartTag: 40,
    bogusComment: 41,
    markupDeclarationOpen: 42,

    commentStart: 43,
    commentStartDash: 44,
    comment: 45,
    commentLessThanSign: 46,
    commentLessThanSignBang: 47,
    commentLessThanSignBangDash: 48,
    commentLessThanSignBangDashDash: 49,
    commentEndDash: 50,
    commentEnd: 51,
    commentEndBand: 52,

    doctype: 53,
    beforeDoctypeName: 54,
    doctypeName: 55,
    afterDoctypeName: 56,
    afterDoctypePublicKeyword: 57,
    beforeDoctypePublicIdentifier: 58,
    doctypePublicIdentifierDoubleQuoted: 59,
    doctypePublicIdentifierSingleQuoted: 60,
    afterDoctypePublicIdentifier: 61,
    betweenDoctypePublicAndSystemIdentifiers: 62,
    afterDoctypeSystemKeyword: 63,
    beforeDoctypeSystemIdentifier: 64,
    doctypeSystemIdentifierDoubleQuoted: 65,
    doctypeSystemIdentifierSingleQuoted: 66,
    afterDoctypeSystemIdentifier: 67,
    bogusDoctype: 68,

    cdataSection: 69,
    cdataSectionBracket: 70,
    cdataSectionEnd: 71,

    characterReference: 72,
    namedCharacterReference: 73,
    ambiguousAmpersand: 74,
    numericCharacterReference: 75,
    hexadecimalCharacterReferenceStart: 76,
    decimalCharacterReferenceStart: 77,
    hexadecimalCharacterReference: 78,
    decimalCharacterReference: 79,
    numericCharacterReferenceEnd: 80
};
